### ISSUE TITLE
Detecting cursor position incorrectly when moving window

### ISSUE THREAD

**Issue by antiaim** [coderedart/egui_overlay#1]
- Running the example, there seems to be an issue with moving windows, however it works correctly when interacting inside the window, as shown:

https://user-images.githubusercontent.com/14151292/190216408-90375166-42c0-4d14-aca0-d37696cfbfe4.mp4

**Comment by coderedart** [comment]
are you using a hidpi monitor?

it seems like this *might be* a scaling issue.

**Comment by antiaim** [comment]
OS: Windows 10 Home 10.0.19044
1920x1080

It does indeed seem to be a High DPI related scaling issue, it was "fixed" by making the OS handle scaling in compatibility settings. Unfortunately it does also make the application somewhat blurry. 

https://user-images.githubusercontent.com/14151292/190257051-e31d13cd-ecee-41a0-8418-d622b5913348.mp4

**Comment by coderedart** [comment]
try the latest commit. i now use a simulated scale instead of actual monitor scale. and the window will be resized by glfw according to the monitor's scale automatically.

**Comment by antiaim** [comment]
Seems to work correctly. Thanks for the help. 👍
