### ISSUE TITLE
How to draw simple shapes

### ISSUE THREAD

**Issue by MrAliSalehi** [coderedart/egui_overlay#13]
Im trying to draw some shapes using `three_d` but I cant figure out a way to draw hollow objects (you know why LoL).

it seems that `three_d` fills the objects by default and there is no way to change it, Im wondering if you know any solution.

the starting point:

```rust
let camera = Camera::new_2d(Viewport::new_at_origo(
    glfw_backend.framebuffer_size_physical[0],
    glfw_backend.framebuffer_size_physical[1]));


let gm = Gm::new(Circle::new(&three_d_backend.context, vec2(100.0, 200.0), 30.0),
                 ColorMaterial::default());

RenderTarget::<'_>::screen(
    &three_d_backend.context,
    glfw_backend.framebuffer_size_physical[0],
    glfw_backend.framebuffer_size_physical[1])
    .clear(ClearState::color_and_depth(0.0, 0.0, 0.0, 0.0, 1.0))
    .render(&camera, std::iter::once(gm), &[]);
```

I also opened a discussion in `three_d` repo: https://github.com/asny/three-d/discussions/425

**Comment by coderedart** [comment]
response at https://github.com/asny/three-d/discussions/425 .

**Comment by MrAliSalehi** [comment]
thank you for your response, im not sure if this question is related to three_d discussion or not.

you mentioned some libraries in the discussion, are those compatible with egui overlay? is there an example?
im going to paint a lot of 3D shapes so...
