### ISSUE TITLE
Flickering issue on windows

### ISSUE THREAD

**Issue by Dissssy** [coderedart/egui_overlay#14]
I'm writing a search utility that has overlay windows that will resize automatically as search results come in from various different sources, and as the window shrinks it leaves behind artifacts that flicker in and out (presumably being left in one of the buffers) my guess is they arent being cleared correctly? Is there something I can do?

**Comment by Dissssy** [comment]
[demo video of whats going on, I forgot i turned off the fancy shadows because they just become black round blobs](https://ass.deadlyneurotox.in/homely-entire-kosher-rude-next-utahprairiedog/direct)

**Comment by MrAliSalehi** [comment]
i have the same problem, I think its related to egui and not directly to this overlay

**Comment by Dissssy** [comment]
unfortunate, its very odd behavior for sure.

**Comment by coderedart** [comment]
yeah. that's egui, and not really related to overlay. you can ask on egui repo instead. or on egui discord.

**Comment by MrAliSalehi** [comment]
@Dissssy if you opened an issue please share it here🙏

**Comment by coderedart** [comment]
you will have the best chance of getting an answer if you can provide a small reproducible example. There's already plenty of issues if you search on egui's github repo. But without a proper reproducible example, its very hard to diagnose (and fix) it.

**Comment by Dissssy** [comment]
Much appreciated, I might someday and if i do ill definitely mention it here, but this is just a small side project and doesn't bother me that much, I just figured i was missing something obvious, thank you though!

**Comment by MrAliSalehi** [comment]
@coderedart 
I tried reproducing this issue with egui and It didn't happen, I think the problem is actually the overlay,
it gets worse when you try to draw with the painter on the screen, it actually doesn't erase the previous frame and show everything

**Comment by coderedart** [comment]
do you have a small reproducible example that i can test?

**Comment by MrAliSalehi** [comment]
you can run the examples, it would cause the same thing, I also sent you a video on discord, check it out)

**Comment by coderedart** [comment]
try running `cargo update` to use `egui_render_glow 0.6.0`. I forgot to disable scissor test before clearing the surface. pretty stupid mistake. So, it only cleared the part where scissor region was set in the last frame. 

If it doesn't work, reopen the issue.
