### ISSUE TITLE
upgrading egui to 0.24.1

### ISSUE THREAD

**Issue by MrAliSalehi** [coderedart/egui_overlay#15]
Hi there, me again :D 
I tried to do it myself: https://github.com/MrAliSalehi/egui_overlay/commit/3ab863e597c4b0dfbfa981b12cd6b5874e95b230
but i'm not sure if I handled the breaking changes correctly, I just changed the code until it compiled and ran my demo successfully.

if it looks good to you I'll open a PR, otherwise I would appreciate if you could help on this :D 
thanks

**Comment by coderedart** [comment]
sure, open a pr. i was delaying it due to the viewport feature, but i can do that later anyway.

**Comment by MrAliSalehi** [comment]
thanks! I'll be using git version for now, waiting for new cargo version

**Comment by coderedart** [comment]
text is broken on my hidpi monitor. I will release a new version after fixing it. (maybe 10 minutes max)

**Comment by coderedart** [comment]
done. just needed to fix scaling which is passed through a separate viewport info inside raw input.

`0.6.0` released.
