### ISSUE TITLE
how to close the overlay completely

### ISSUE THREAD

**Issue by MrAliSalehi** [coderedart/egui_overlay#18]
im looking for a way to end the app inside the `gui_run`.
I know there is a `Window::open(bool)` which can "hide" the egui and not even the glfw itself, but its not really helpful,

I also found `glfw_backend.window.close()` which says it closes the glfw and "perhaps" the overlay as well, but it moves the window property which is behind a reference, so it wont compile.

is there any solution?

**Comment by coderedart** [comment]
[`window.set_should_close(true)`](https://docs.rs/glfw-passthrough/0.51.1/glfw_passthrough/struct.Window.html#method.set_should_close).

[egui_overlay](https://github.com/coderedart/egui_overlay/blob/master/src/lib.rs#L183C20-L183C28) checks every frame if that is true or false, and exits the loop if it is true.

**Comment by MrAliSalehi** [comment]
thanks!

I'm trying to do `egui_overlay::start` inside another overlay
I made a function called `startup` in the `EguiOverlay` Trait :
```rust
fn startup(
      &mut self, // this could be dangerous due to user being able to call self.startup..etc and create infinite recursion
      egui_context: &mut Context,
      default_gfx_backend: &mut DefaultGfxBackend,
      glfw_backend: &mut GlfwBackend) {
      println!("overlay starting...");
  }
```
and at the end of the `start` function I did this:

```rust
let mut egui_context = Context::default();

user_data.startup(
    &mut egui_context,
    &mut default_gfx_backend,
    &mut glfw_backend,
);

let overlap_app = OverlayApp {
    user_data,
    egui_context,
    default_gfx_backend,
    glfw_backend,
};
overlap_app.enter_event_loop();
```

my goal was to write some stuff that are meant to be executed only once and not be repeated inside the main even loop, wasn't sure if its helpful enough for other ppls to open a PR for it or not, but anyway, my startup function looks like this:
```rust
// MyOverlay, this is the main entry point
fn startup(&mut self, _: &mut Context, _: &mut ThreeDBackend, glfw_backend: &mut GlfwBackend) {
    let (sender, receiver) = bounded::<()>(1);    
    // do some initial stuff
    thread::spawn( || loop { 
        if x == y { 
            sender.send(());  //abort the waiter
            break;
         }
    });
    egui_overlay::start(WaitingWindow::new(receiver));
    //cleanup
}
```
which is basically blocking the startup function until the signal is sent through the channel:

```rust
// Waiting window
impl EguiOverlay for WaitingWindow {
    fn startup(&mut self, egui_context: &mut Context, default_gfx_backend: &mut ThreeDBackend, glfw_backend: &mut GlfwBackend) {
        glfw_backend.window.set_pos(0, 0);
        glfw_backend.window.set_size(500, 500);
    }
    fn gui_run(&mut self, egui_context: &Context, _: &mut ThreeDBackend, glfw_backend: &mut GlfwBackend) {
        Window::new("WAITING")
            .default_size([250.0, 150.0])
            .show(egui_context, |ui| {
                match self.rec.try_recv() {
                    Ok(_) => {
                        ui.label("okay no more waiting.");
                        sleep(Duration::from_millis(400));
                        glfw_backend.window.set_should_close(true);
                    }
                    Err(_) => {
                        ui.label("waiting...");
                    }
                }
                ui.allocate_space(Vec2::new(250.0, 150.0));
            });
        if egui_context.wants_pointer_input() || egui_context.wants_keyboard_input() {
            glfw_backend.window.set_mouse_passthrough(false);
        } else {
            glfw_backend.window.set_mouse_passthrough(true);
        }
        egui_context.request_repaint();
    }
}
```
every thing works fine
but then, when the signal is sent and the `WaitingWindow` is closed, program panics with the following error:

```
thread '<unnamed>' panicked at 'expected non-zero GL name', \glow-0.12.3\src\native.rs:114:35
  17:     0x7ff7931c22e8 - glow::native::non_zero_gl_name
                               at \glow-0.12.3\src\native.rs:114
  18:     0x7ff7931c24d9 - glow::native::impl$2::create_texture
                               at\glow-0.12.3\src\native.rs:242
  19:     0x7ff7931a58d9 - egui_render_glow::Painter::prepare_render
                               at  egui_overlay\crates\egui_render_glow\src\lib.rs:274
  20:     0x7ff7931a1889 - egui_render_glow::GlowBackend::render_egui
                               at  egui_overlay\crates\egui_render_glow\src\lib.rs:143
  21:     0x7ff793193570 - egui_render_three_d::ThreeDBackend::render_egui
                               at  egui_overlay\crates\egui_render_three_d\src\lib.rs:58
  22:     0x7ff793112f18 - egui_overlay::EguiOverlay::run<MyOverlay>
                               at  egui_overlay\src\lib.rs:127
  23:     0x7ff793148187 - egui_overlay::impl$0::enter_event_loop::closure$0<MyOverlay>
                               at  egui_overlay\src\lib.rs:175
  24:     0x7ff793146f23 - egui_overlay::OverlayApp<MyOverlay>::enter_event_loop<MyOverlay>
                               at  egui_overlay\src\lib.rs:200
  25:     0x7ff793148747 - egui_overlay::start<MyOverlay>
                               at  egui_overlay\src\lib.rs:79
```
i guess its because somewhere the glfw is being modified or somehow one instance of it is being used across the application, IDK but calling the `glfw_backend.window.set_should_close(true);` causes to `MyOverlay` (the main one) fail to start, I understand this problem is happening due to the modifications I did to the `egui_overlay` but I'm thinking these 2 could be a part of the library itself, 1)creating "waiting Windows" or basically any custom window and 2)hooking to the startup state of app, I could open a PR for it if you are okay with it and we manage to solve this weird issue. Thanks.

**Comment by coderedart** [comment]
that is too complicated to be in this library. `egui_overlay` is only supposed to serve as a bare minimum example. As the README mentions

> For advanced usecases, i recommend directly using egui_window_glfw_passthrough crate directly with either wgpu or three-d or glow backend crates. As you can see in lib.rs, its barely 150 lines of code to set up. It will allow you more control over event loop, as well as drawing.

I avoided a startup function and multi-windows on purpose. There are some quirks of egui like fonts only initializing after the first frame. Then, with multiple windows, we need to deal with making opengl contexts current or separating the events for different windows etc.. which all brings in more complexity. 

For the startup function, the simplest approach is to simply have a `bool` called `first_frame` in your UserData. Set it `true` before entering event loop. Inside `gui_run` fn, check if bool is `true`, and call your start up code. Then, set it to false once you are ready, so that from next frame, you won't call your start up code.

> somehow one instance of it is being used across the application,

yeah, event listening and some other window code is "global", so, creating multiple glfw contexts is bad. To support multiple windows, the change needs to come from glfw and glow crates. I need to do that anyway for "viewports" feature of 0.24 egui, but i am busy with something else until jan 4th.

**Comment by MrAliSalehi** [comment]
uh I guess that makes sense, any idea for the splash screen? should i create 2 windows in gui_run and render them conditionally? like the "startup" logic ?

**Comment by coderedart** [comment]
yep. just store a bool or an enum that represents what state you are in. And only render that state. For splash screen (something like discord's), you probably want to use an `Area` instead of a `Window` to avoid that titlebar.

**Comment by MrAliSalehi** [comment]
alright, thanks!
