### ISSUE TITLE
Request: add license to determine allowed use cases

### ISSUE THREAD

**Issue by FreddyFunk** [coderedart/egui_overlay#19]
Hi @coderedart :) This project has currently no license specified. I tought about using egui_overlay in some of my egui projects but I could not, since I am not sure if I am licensed to do so or not. Might it be possible to add a license that is compatible with egui itself and use ideally the same license? egui uses a dual license of Apache-2.0 and MIT license, like most other open source rust projects.

**Comment by coderedart** [comment]
https://github.com/coderedart/egui_overlay/blob/master/Cargo.toml#L46 :)

I can add Apache in the next version (unless you need it right now).

**Comment by FreddyFunk** [comment]
Oh, thanks :D MIT is the best license for my use case. I was not aware of the license notice in the Cargo.toml. Maybe just adding a license file with the MIT license to this repo would be enough, since it will be picked up by GitHub and automatically highlighted, so it can be seen at first glance.

**Comment by coderedart** [comment]
https://github.com/coderedart/egui_overlay/blob/master/LICENSE 

done :)
