### ISSUE TITLE
Usage with GL

### ISSUE THREAD

**Issue by HoyerHub** [coderedart/egui_overlay#2]
Hello, wgpu can't compile on my ubuntu machine for some reason, so I need to use OpenGL backend. Can you please provide some guidance on how to do that?

**Comment by HoyerHub** [comment]
I figured it out using https://crates.io/crates/egui_render_glow - even though it states it's merged into egui_backend, I couldn't figure it out without it

**Comment by coderedart** [comment]
haven't published the latest version of `egui_backend` crate yet.

Multiple crate are a pain, so i am just putting all backends (glfw/winit/sdl2 as well as wgpu/opengl) in the same crate behind feature gates. will soon merge it after i properly check hidpi support on all of them on linux + windows.
