### ISSUE TITLE
Add Cargo.toml for every example

### ISSUE THREAD

**Issue by FreePhoenix888** [coderedart/egui_overlay#24]

**Comment by coderedart** [comment]
why?

**Comment by FreePhoenix888** [comment]
Because we have no idea which dependency versions are used for examples

Look at egui examples: https://github.com/emilk/egui/tree/master/examples/keyboard_events
They are easy to copy-and-use

**Comment by coderedart** [comment]
Done https://github.com/coderedart/egui_overlay/commit/511bac2757d4aeb3b717fc78d3b6ce85038e4075

**Comment by FreePhoenix888** [comment]
Thank you!
