### ISSUE TITLE
Black background with wrong mouse position handling when fullscreen

### ISSUE THREAD

**Issue by FreePhoenix888** [coderedart/egui_overlay#26]
https://github.com/coderedart/egui_overlay/assets/66206278/e084d1a6-8232-45db-af56-af90f8ef1dfb

https://github.com/coderedart/egui_overlay/assets/66206278/2dfe84e2-5aa6-4e58-85d1-7f0c6e96347d

**Comment by coderedart** [comment]
That's a limitation of glfw/platform from the older days. When a window goes fullscreen, it gets "exclusive" access to desktop and nothing else is rendered. 

The workaround I use is to resize the window to `width - 1` and `height - 1` where width and height are dimensions of the screen. This keeps the window *just* less than fullscreen dimensions to not trigger the black screen.

**Comment by FreePhoenix888** [comment]
> That's a limitation of glfw/platform from the older days. When a window goes fullscreen, it gets "exclusive" access to desktop and nothing else is rendered.

Where have you learned this info from?

**Comment by coderedart** [comment]
@FreePhoenix888 mostly from search results when I was debugging this issue in the past https://devblogs.microsoft.com/directx/demystifying-full-screen-optimizations/ . `fullscreen transparent window` should give you a few google results. 

The workaround was good enough for my use case, so I never bothered going further.  Fullscreen also messes with `always on top` order flag, so the workaround was pretty much the only way forward.
