### ISSUE TITLE
How to make window resizable?

### ISSUE THREAD

**Issue by Coaixy** [coderedart/egui_overlay#28]
![code](https://github.com/coderedart/egui_overlay/assets/60541541/3da9ea4a-bfbe-4320-bf35-8b6aea0688ba)

I set resizable true ,
but i can not resize this window.

I'm a noob, thanks for your help。

**Comment by coderedart** [comment]
This is an `egui` question tbh which can be asked at https://github.com/emilk/egui/discussions or egui discord

But basically, the window will be atleast as bit as its title frame. 

So, try something like 
```rust
egui::Window::new("Hi").resizable(true).show(egui_context, |ui| {
	for i in 0..3 {
		ui.label("A long sentence that is bigger than title length");
	}
});
```

Now, you should be able to resize it.
