### ISSUE TITLE
Can't compile on windows

### ISSUE THREAD

**Issue by And329** [coderedart/egui_overlay#33]
This is what i get
`cargo build
   Compiling owned_ttf_parser v0.20.0
   Compiling glfw-sys-passthrough v4.0.3+3.3.5
   Compiling bytemuck_derive v1.6.0
   Compiling zerocopy-derive v0.6.6
   Compiling thiserror-impl v1.0.59
   Compiling approx v0.4.0
error: failed to run custom build command for `glfw-sys-passthrough v4.0.3+3.3.5`

Caused by:
  process didn't exit successfully: `C:\Users\zen\Desktop\egui_overlay-0.8.0\target\debug\build\glfw-sys-passthrough-967231a75b085014\build-script-build` (exit code: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "C:\\Users\\zen\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\glfw-sys-passthrough-4.0.3+3.3.5\\." "-G" "Visual Studio 17 2022" "-Thost=x64" "-Ax64" "-DGLFW_BUILD_EXAMPLES=OFF" "-DGLFW_BUILD_TESTS=OFF" "-DGLFW_BUILD_DOCS=OFF" "-DCMAKE_INSTALL_LIBDIR=lib" "-DGLFW_BUILD_WAYLAND=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\zen\\Desktop\\egui_overlay-0.8.0\\target\\debug\\build\\glfw-sys-passthrough-06cdb8674a500be3\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Debug"

  --- stderr
  thread 'main' panicked at C:\Users\zen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1098:5:

  failed to execute command: program not found
  is `cmake` not installed?

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...`

**Comment by coderedart** [comment]
> failed to execute command: program not found
> is cmake not installed?

you need cmake installed to build glfw crate. just install cmake and reboot.

**Comment by coderedart** [comment]
reopen issue if your problem is still not solved.
