### ISSUE TITLE
Cannot compile on windows

### ISSUE THREAD

**Issue by lngex** [coderedart/egui_overlay#39]
`E:\rust\project\egui_overlay-master>cargo run -p basic
   Compiling glfw-sys-passthrough v4.0.3+3.3.5
warning: unexpected `cfg` condition name: `wasm32`
   --> crates\egui_render_glow\src\lib.rs:224:25
    |
224 |                 if cfg!(wasm32) {
    |                         ^^^^^^ help: found config with similar value: `target_arch = "wasm32"`
    |
    = help: expected names are: `clippy`, `debug_assertions`, `doc`, `docsrs`, `doctest`, `feature`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `test`, `ub_checks`, `unix`, and `windows`
    = help: consider using a Cargo feature instead
    = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
             [lints.rust]
             unexpected_cfgs = { level = "warn", check-cfg = ['cfg(wasm32)'] }
    = help: or consider adding `println!("cargo::rustc-check-cfg=cfg(wasm32)");` to the top of the `build.rs`
    = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
    = note: `#[warn(unexpected_cfgs)]` on by default

warning: `egui_render_glow` (lib) generated 1 warning
error: failed to run custom build command for `glfw-sys-passthrough v4.0.3+3.3.5`

Caused by:
  process didn't exit successfully: `E:\rust\project\egui_overlay-master\target\debug\build\glfw-sys-passthrough-cf2e966dc8d5f954\build-script-build` (exit code: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "E:\\rust\\tool\\.cargo\\registry\\src\\mirrors.aliyun.com-8754fae0eb2f08f1\\glfw-sys-passthrough-4.0.3+3.3.5\\." "-G" "Visual Studio 17 2022" "-Thost=x64" "-Ax64" "-DGLFW_BUILD_EXAMPLES=OFF" "-DGLFW_BUILD_TESTS=OFF" "-DGLFW_BUILD_DOCS=OFF" "-DCMAKE_INSTALL_LIBDIR=lib" "-DGLFW_BUILD_WAYLAND=OFF" "-DCMAKE_INSTALL_PREFIX=E:\\rust\\project\\egui_overlay-master\\target\\debug\\build\\glfw-sys-passthrough-ba98dc26f69f9e6e\\out" "-DCMAKE_C_FLAGS= -nologo -MT -Brepro" "-DCMAKE_C_FLAGS_DEBUG= -nologo -MT -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MT -Brepro" "-DCMAKE_CXX_FLAGS_DEBUG= -nologo -MT -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MT -Brepro" "-DCMAKE_ASM_FLAGS_DEBUG= -nologo -MT -Brepro" "-DCMAKE_BUILD_TYPE=Debug"
  -- Selecting Windows SDK version 10.0.26100.0 to target Windows 10.0.19045.
  -- The C compiler identification is unknown
  -- Configuring incomplete, errors occurred!

  --- stderr
  CMake Error at CMakeLists.txt:3 (project):
    No CMAKE_C_COMPILER could be found.

  thread 'main' panicked at E:\rust\tool\.cargo\registry\src\mirrors.aliyun.com-8754fae0eb2f08f1\cmake-0.1.51\src/lib.rs:1100:5:

  command did not execute successfully, got: exit code: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by Loara228** [comment]
download [cmake](https://cmake.org/download/) (Windows x64 Installer)
https://github.com/coderedart/egui_overlay/issues/33
