### ISSUE TITLE
Panic on start when the only egui ui objects are drawn outside of a 800px by 600px window

### ISSUE THREAD

**Issue by chastise** [coderedart/egui_overlay#4]
Specifically, the painter in egui_render_wgpu panics with the message `vertex buffer length should not be zero`.

I'm working with a local egui_overlay crate, and this is easily fixed by modifying start_egui_overlay() to accept and set glfw_backend window size parameters:

```rust
pub fn start_egui_overlay(app: impl UserApp<egui_window_glfw_passthrough::GlfwWindow, egui_render_wgpu::WgpuBackend> + 'static, screen_width: i32, screen_height: i32) {
    let mut glfw_backend =
        egui_window_glfw_passthrough::GlfwWindow::new(Default::default(), Default::default());
    let wgpu_backend = egui_render_wgpu::WgpuBackend::new(&mut glfw_backend, Default::default());

    glfw_backend.window.set_size(screen_width, screen_height);
    glfw_backend.run_event_loop(wgpu_backend, app);
}
```

As far as I can tell, you need to set this before calling `glfw_backend.run_event_loop(...)` because changes made to glfw_backend from within the event loop don't take effect until the second framedraw.

**Comment by chastise** [comment]
I'm pretty new to rust and egui, but I would be happy to submit a PR with the above fix included. I'm not sure if there's a better / more idiomatic way to fix this, and I also don't know whether it's desired behavior for this panic to happen when there are no egui widgets being drawn in general. In my case, I stumbled upon this because I'm building an overlay and was testing initializing the overlay on the far-right side of my 1920x1080 screen.

**Comment by coderedart** [comment]
It seems i somehow missed this issue completely. I have no idea how i missed this for six months -_-.

Anyway, This should probably be fixed at this point, so i will close this issue. But if you have any problem, feel free to open it again.
