### ISSUE TITLE
Change examples to use versioning from crates.io instead of repo

### ISSUE THREAD

**Issue by CheetoTrump** [coderedart/egui_overlay#41]
Change examples to use versioning from crates.io instead of repo

i want to simply copy the example code and add the crates.io stuff to toml, not download the whole repo then gut, its annoying but maybe im just lacking braincells

**Comment by coderedart** [comment]
Its just convenient to test using examples if the dependencies are by path into the workspace. egui does it the same way https://github.com/emilk/egui/blob/master/examples/confirm_exit/Cargo.toml .
