### ISSUE TITLE
expected `egui::context::Context`, found `egui::Context`

### ISSUE THREAD

**Issue by yatoiv** [coderedart/egui_overlay#42]
Using any of the examples in egui_overlay with any version of egui above 0.26.2 results into an error

```rust
    fn gui_run(
        &mut self,
        egui_context: &egui::Context,
        _default_gfx_backend: &mut ThreeDBackend,
        glfw_backend: &mut egui_window_glfw_passthrough::GlfwBackend,
    ) { 
    
error[E0053]: method `gui_run` has an incompatible type for trait
   --> src/main.rs:114:23
    |
114 |         egui_context: &egui::Context,
    |                       ^^^^^^^^^^^^^^ expected `egui::context::Context`, found `egui::Context`
    |
    = note: expected signature `fn(&mut HelloWorld, &egui::context::Context, &mut ThreeDBackend, &mut GlfwBackend)`
               found signature `fn(&mut HelloWorld, &egui::Context, &mut ThreeDBackend, &mut GlfwBackend)`
help: change the parameter type to match the trait
    |
114 |         egui_context: &egui::context::Context,
    |                       ~~~~~~~~~~~~~~~~~~~~~~~
```
switching `egui_context` to `egui::context::Context` results in error: `Module "context" is private`

**Comment by coderedart** [comment]
Its just version mismatch. https://github.com/coderedart/egui_overlay/blob/master/Cargo.toml#L27 this repo was written against 0.26 and never updated. 

Cargo's semantic versioning assumes that when major version is zero, a minor version upgrade is a breaking change and thus the types from both versions are different (even if nothing actually changed in the code). I am a little busy at the moment with another project. I will update the dependencies within a week (or hopefully someone else sends a PR before then).

**Comment by yatoiv** [comment]
> Its just version mismatch. https://github.com/coderedart/egui_overlay/blob/master/Cargo.toml#L27 this repo was written against 0.26 and never updated.
> 
> Cargo's semantic versioning assumes that when major version is zero, a minor version upgrade is a breaking change and thus the types from both versions are different (even if nothing actually changed in the code). I am a little busy at the moment with another project. I will update the dependencies within a week (or hopefully someone else sends a PR before then).

Rebuilding this library alone against newer version won't work, it has to to be done for `egui_window_glfw_passthrough` and `egui_render_three_d` as well

**Comment by coderedart** [comment]
egui bumped to 0.29 now. look at egui_overlay 0.9 version.
