### ISSUE TITLE
Black rectangle obscures content on Xorg/i3

### ISSUE THREAD

**Issue by vi** [coderedart/egui_overlay#43]
When running the `triangle` example, I expect it to show a triangle and two egui windows (like in the video in README).
But instead I see big a black rectangle, containing both the triangle and the windows. The rectangle obscures all underlying content (though indeed passes through input events).

![blackrect](https://github.com/user-attachments/assets/ce6a115a-4809-43c0-bd03-10de2bb174eb)

Here the main window is non-fullscreen, but it is the same if it is fullscreen.

**Comment by vi** [comment]
Also the window is treated by i3 as a usual window, unlike e.g. in [this example](https://stackoverflow.com/a/57780772) where the window stays on top of everything and ignores e.g. switched workspaces, fullscreen apps, etc.

**Comment by coderedart** [comment]
The black background indicates the lack of a compositor. @vi Are you using a compositor that supports transparency? (eg: picom). Try checking with a transparent terminal first.  

The example you linked uses raw X11 to bypass the window manager. Glfw only supports portable features and respects the window manager.

i3 is a tiling wm, and doesn't respect all x11 hints. It supports disabling titlebar and borders. But it ignores manual position/size hints. Overlays are floating windows and go against the spirit of tiling. You must use i3 config to make special rules for your application. 

Use config to make your window "floating". These are always on top of all tiling windows. But maintaining one floating window on top of another is [out of scope for i3](https://github.com/i3/i3/issues/4478).

[Sticky windows](https://i3wm.org/docs/userguide.html#_sticky_floating_windows) config exists to make a window visible regardless of workspace.

**Comment by vi** [comment]
Starting/stopping `picom` reveals/hides the background.

Maybe the fact that a compositor is needed should be mentioned in the README (preferably with `picom` name nearby)

**Comment by coderedart** [comment]
Great. I will mention it in the README.
