### ISSUE TITLE
Egui Overlay 0.4.0 no longer compiles on Windows

### ISSUE THREAD

**Issue by Michal-Miko** [coderedart/egui_overlay#5]
I am unable to compile the latest example on Windows 11.

Rustc version info:
```
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-pc-windows-msvc / x86_64-pc-windows-gnu
release: 1.70.0
LLVM version: 16.0.2
```

The previous version's example ([0.2.3](https://github.com/coderedart/egui_overlay/tree/ed1416c723dae0d5acb2493fbb6594941e5541a0)) compiled successfully after manually changing the version of `egui_render_wgpu` to 0.3.0 since 0.2.0 is no longer available. When I try to run the latest example with version 0.4.0, I get the following linking errors:
```
libegui_window_glfw_passthrough-1f6d82a8caffee04.rlib(egui_window_glfw_passthrough-1f6d82a8caffee04.egui_window_glfw_passthrough.59083b27-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol emscripten_get_element_css_size referenced in function _ZN89_$LT$egui_window_glfw_passthrough..GlfwBackend$u20$as$u20$egui_backend..WindowBackend$GT$15get_window_size17h6f4d3532e19f330aE
libegui_window_glfw_passthrough-1f6d82a8caffee04.rlib(egui_window_glfw_passthrough-1f6d82a8caffee04.egui_window_glfw_passthrough.59083b27-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol emscripten_set_element_css_size referenced in function _ZN89_$LT$egui_window_glfw_passthrough..GlfwBackend$u20$as$u20$egui_backend
```

Should `egui_window_glfw_passthrough` be referencing emscripten functions when targeting windows?
https://github.com/coderedart/etk/blob/d9785419c6b6969056bba050e8ff0170134f78be/crates/egui_window_glfw_passthrough/src/lib.rs#L323
https://github.com/coderedart/etk/blob/d9785419c6b6969056bba050e8ff0170134f78be/crates/egui_window_glfw_passthrough/src/lib.rs#L348

**Comment by coderedart** [comment]
ah, my bad. I forgot to feature gate it properly.

**Comment by coderedart** [comment]
@Michal-Miko can you run `cargo update` to bump `egui_window_glfw_passthrough` to `0.4.1` and see if it fixes the issues?

**Comment by Michal-Miko** [comment]
It compiles properly now, thanks!
